imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            commands:
                - composer self-update --2
            environment:
                variables:
                    COMPOSER_MAJOR_VERSION: 2 
                php:
                    version: 8.3.11
        analysis:
            commands:
                - composer self-update --2
                - php-scrutinizer-run
                #- phpcs-run # Not used, missing config file
            environment:
                variables:
                    COMPOSER_MAJOR_VERSION: 2
            #tests:
            #    override:
            #        - composer self-update --2
            #        - composer --version 
            #        - php-scrutinizer-run
            #        #- phpcs-run # Not used, missing config file
    tests:
        override:
            -   command: "composer phpunit"
                # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
