imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            commands:
                - curl -sS https://getcomposer.org/installer | php -- --install-dir=/tmp --filename=composer  # Install Composer to /tmp
                - mv /tmp/composer /usr/local/bin/composer  # Move to /usr/local/bin
                - chmod +x /usr/local/bin/composer  # Make it executable
                - /usr/local/bin/composer --version  # Verify version
            environment:
                php:
                    version: 8.3.11
        analysis:
            commands:
                - curl -sS https://getcomposer.org/installer | php -- --install-dir=/tmp --filename=composer  # Install Composer to /tmp
                - mv /tmp/composer /usr/local/bin/composer  # Move to /usr/local/bin
                - chmod +x /usr/local/bin/composer  # Make it executable
                - /usr/local/bin/composer --version  # Verify version
                - php-scrutinizer-run
            environment:
                variables:
                    COMPOSER_MAJOR_VERSION: 2

    tests:
        override:
            - command: "/usr/local/bin/composer phpunit"
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
