imports:
    - php

filter:
    excluded_paths: [vendor/*, test/* src/Controller/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            commands:
                - composer self-update --2
            environment:
                php:
                    version: 8.3.3
                    # version: 8.1.13
                    # version: 8.1.17
                    # version: 8.2.4
        analysis:
            environment:
                php:
                    version: 8.3.3
            tests:
                override:
                    - php-scrutinizer-run
                    #- phpcs-run # Not used, missing config file
        coverage:
            environment:
                php:
                    version: 8.3.3
            tests:
                override:
                    -   command: "composer phpunit"
                        # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                        coverage:
                            file: "docs/coverage.clover"
                            format: "php-clover"